package br.jhonatastomaz.interfaces;

import java.util.Date;
import java.util.List;

import br.jhonatastomaz.implementations.models.ConfigOption;
import br.jhonatastomaz.implementations.models.CustomField;

public interface IService {
	    int getId();
	    void setId(int id);
	    int getClientId();
	    void setClientId(int clientId);
	    int getOrderId();
	    String getOrderNumber();
	    int getPid();
	    void setPid(int pid);
	    Date getRegDate();
	    void setRegDate(Date regDate);
	    String getName();
	    void setName(String name);
	    String getTranslatedName();
	    void setTranslatedName(String translatedName);
	    String getGroupName();
	    void setGroupName(String groupName);
	    String getTranslatedGroupName();
	    void setTranslatedGroupName(String translatedGroupName);
	    String getDomain();
	    void setDomain(String domain);
	    String getDedicatedIp();
	    void setDedicatedIp(String dedicatedIp);
	    int getServerId();
	    void setServerId(int serverId);
	    String getServerName();
	    void setServerName(String serverName);
	    String getServerIp();
	    void setServerIp(String serverIp);
	    String getServerHostname();
	    void setServerHostname(String serverHostname);
	    String getSuspensionReason();
	    void setSuspensionReason(String suspensionReason);
	    double getFirstPaymentAmount();
	    void setFirstPaymentAmount(double firstPaymentAmount);
	    double getRecurringAmount();
	    void setRecurringAmount(double recurringAmount);
	    String getPaymentMethod();
	    void setPaymentMethod(String paymentMethod);
	    String getPaymentMethodName();
	    void setPaymentMethodName(String paymentMethodName);
	    String getBillingCycle();
	    void setBillingCycle(String billingCycle);
	    Date getNextDueDate();
	    void setNextDueDate(Date nextDueDate);
	    String getStatus();
	    void setStatus(String status);
	    String getUsername();
	    void setUsername(String username);
	    String getPassword();
	    void setPassword(String password);
	    String getSubscriptionId();
	    void setSubscriptionId(String subscriptionId);
	    int getPromoId();
	    void setPromoId(int promoId);
	    String getOverideAutoSuspend();
	    void setOverideAutoSuspend(String overideAutoSuspend);
	    Date getOverideSuspendUntil();
	    void setOverideSuspendUntil(Date overideSuspendUntil);
	    String getNs1();
	    void setNs1(String ns1);
	    String getNs2();
	    void setNs2(String ns2);
	    String getAssignedIps();
	    void setAssignedIps(String assignedIps);
	    String getNotes();
	    void setNotes(String notes);
	    int getDiskUsage();
	    void setDiskUsage(int diskUsage);
	    int getDiskLimit();
	    void setDiskLimit(int diskLimit);
	    int getBwUsage();
	    void setBwUsage(int bwUsage);
	    int getBwLimit();
	    void setBwLimit(int bwLimit);
	    Date getLastUpdate();
	    void setLastUpdate(Date lastUpdate);
	    List<CustomField> getCustomFields();
	    void setCustomFields(List<CustomField> customFields);
	    List<ConfigOption> getConfigOptions();
	    void setConfigOptions(List<ConfigOption> configOptions);
	

}
